### ISSUE TITLE
Optimizing textures to square resulted in animated textures not working and having graphical glitches due to animation strips becoming crushed into one frame

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#475]
:edit: most of these are good now. Skip down to the "From other mods" section and its `####` subsections to see a list of remaining textures to revert in 211111a.

Most list items here are low-priority other than the following sections.
- Palettes
- Animation Strips
- Get the higher res version
- Wrong _inv image

## Animation Strips
animation strips not working due to being stretched
- mods/coderbuild/coderblocks/textures
  - [x] ocean_sea_lantern.png
  - [x] xdecor_lantern.png
- mods/coderbuild/xdecor/textures/
  - [x] xdecor_candle_floor.png
  - [x] xdecor_candle_wall.png
  - [x] xdecor_lantern.png
  - [ ] #480 make these into mesh nodes (moved to separate issue)
- mods/coderbuild/xmasdecor/textures/
  - [x] xmasdecor_lights_multicolor_bulb.png
  - [x] xmasdecor_lights_multicolor.png
  - [x] xmasdecor_lights_white_icicle.png
  - [x] xmasdecor_lights_white.png
- mods/coderbuild/sfnodes/textures/
  - [x] sfnodes_black_screen.png
  - [x] sfnodes_screen.png
  - [x] sfnodes_screen2.png
- mods/coderbuild/chains/textures/
  - [x] chains_candle_flame.png

## Wrong _inv image
The following use an animation strip for the inventory image, which results in a graphical glitch (inventory/wielditem requires a single-frame version of the texture):
- [x] coderblocks:fake_fire should use coderblocks_fake_fire_inv.png for the inventory image (but continue to use coderblocks_fake_fire_animated.png for the node texture)

## Blurry tools
- [ ] #479 (moved to separate issue) 

## Palettes
palettes that don't work since they are stretched and should only have 1 color per pixel due to the way unifieddyes operates:

- mods/coderbuild/coderblocks/textures/
  - [x] unifieddyes_palette_extended.png
- unifieddyes/textures/
  - [x] unifieddyes_palette_extended.png
  - [x] unifieddyes_palette_*s.png: only one row of pixels each, so apparently making them square is ok if you only resize them vertically but keep the upstream horizontal resolution--however, this will only work for ones that are 1 pixel high (unifieddyes will give a warning saying it will be truncated to the first 16 colors for the named palettes (256 are allowed for unifieddyes_palette_extended.png))

## Get the higher res version
- mods/coderbuild/coderblocks/textures/
  - [x] lmb_glowstone.png: texture looks "familiar"...Replace it with a copy of high-res non-derivative art in same directory: glowstone_glowstone.png
- mods/coderbuild/bonemeal/textures: textures look "familiar"...Replace with high-res non-derivative art (recommended action: Set BUCKET_GAME to the Bucket_Game path then `cd EnlivenMinetest && git pull && rsync -rt Bucket_Game-branches/bonemeal-textures--replace $BUCKET_GAME` (also replaces the bonemeal_particle.png with one by Poikilos and bonemeal_bone.png with sapier's animalmaterials one and edits the license appropriately)
  - [x] bonemeal_fertiliser.png
  - [x] bonemeal_mulch.png
  - [x] bonemeal_mulch.png

## Make new animation for steampunk fire
- [ ] #478 (moved to separate issue)

## Status of this texture review issue
Texture directories not listed above weren't examined yet, other than:
- [x] mods/coderbuild/3d_armor/*/
- [x] mods/coderbuild/3d_forniture
- [x] mods/coderbuild/abriflame
- [x] mods/coderbuild/abriglass
- [x] mods/coderbuild/abritorch
- [x] mods/coderbuild/ambience
- [x] mods/coderbuild/anvil
- [x] mods/coderbuild/army
- [x] mods/coderbuild/bakedclay
- [x] mods/coderbuild/bamboo
- [x] mods/coderbuild/basic_materials
- [x] mods/coderbuild/beautiflowers
- [x] mods/coderbuild/beds
- [x] mods/coderbuild/birthstones
- [x] mods/coderbuild/boats
- [x] mods/coderbuild/bonemeal
- [x] mods/coderbuild/books
- [x] mods/coderbuild/boost_cart
- [x] mods/coderbuild/butterflies
- [x] mods/coderbuild/carts
- [x] mods/coderbuild/castle and castle/*/
- [x] mods/coderbuild/cblocks
- [x] mods/coderbuild/christmas_craft
- [x] mods/coderbuild/coderxmas
- [x] any mods in alphabetical order that were missed here should be listed under "from other mods" below if affected
- [x] mods/coderbuild/ropes
- [x] mods/coderbuild/sandplus
- [x] mods/coderbuild/soccer
- [x] mods/coderbuild/stainedglass
- [x] mods/coderbuild/stairsio
- [x] mods/coderbuild/stoneworks
- [x] mods/coderbuild/tnt
- [x] mods/coderbuild/travail
- [x] mods/coderbuild/travelnet
- [x] mods/coderbuild/walls
- [x] mods/coderbuild/xconnected
- [x] mods/coderbuild/xpanes

### From other mods
`~/minetest/games$ ~/git/gimp-plugin-channel-tinker/diffimagesratio.py ../bucket_game-200527 bucket_game --max-source-ratio .5 --exclude projects --exclude src --exclude etc --exclude 3d_armor --exclude signs_lib | grep -v narrower | grep -v "[Ss]creenshot"`
* checking only: ['.png', '.jpg', '.bmp']
* excluding directory names: ['projects', 'src', 'etc', '3d_armor', 'signs_lib']
### wider
My program (see command above) marked these files as "wider" since they are wider than in bucket_game 200527. Some others were marked as such as well, but these specifically look like animation strips when reviewed visually in my image viewer. 
- [x] wider:      bucket_game/mods/decorpack/homedecor/textures/forniture_torch_flame.png
- [x] wider:      bucket_game/mods/decorpack/homedecor/textures/homedecor_embers.png
- [x] wider:      bucket_game/mods/decorpack/homedecor/textures/homedecor_ceiling_fan_top.png
- [x] wider:      bucket_game/mods/decorpack/homedecor/textures/homedecor_clothes_male5_preview.png
- [x] wider:      bucket_game/mods/decorpack/homedecor/textures/homedecor_clothes_female5_preview.png
- [x] wider:      bucket_game/mods/decorpack/homedecor/textures/homedecor_ceiling_fan_bottom.png
- [x] wider:      bucket_game/mods/decorpack/homedecor/textures/homedecor_candle_flame.png
- [x] wider:      bucket_game/mods/coderbuild/xmasdecor/textures/xmasdecor_garland_lights.png
- [x] wider:      bucket_game/mods/coderbuild/nether/textures/nether_portal.png
- [x] wider:      bucket_game/mods/coderbuild/decoblocks/textures/decoblocks_lantern.png
- [x] wider:      bucket_game/mods/coderbuild/decoblocks/textures/decoblocks_glow.png
- [x] wider:      bucket_game/mods/coderbuild/darkage/textures/darkage_palette.png
- [x] wider:      bucket_game/mods/codercore/codersea/textures/starfishsprite.png
- [x] wider:      bucket_game/mods/codercore/codersea/textures/clams_whiteshell.png
- [x] wider:      bucket_game/mods/codercore/default/textures/default_furnace_locked_front_active.png
- [x] wider:      bucket_game/mods/codercore/default/textures/default_furnace_front_active.png

#### unreadable in previous version
PIL can't read these images or they didn't exist in 200527 for comparison, so I didn't review them visually. Review these to ensure they are readable by Minetest if are necessary in 211111a, have the correct file extension, and revert if they are animation strips.
- [x] (resolved as invalid: it isn't an animation strip. Particles are generated by tronportal instead (Note (also not an issue) that the portal aspect of the mod is disabled in bucket_game: see #513 ).) mods/upper_realms/tronrealm/tronportal/textures/tron_portal.png

#### unsure
(only revert if old image is an animation strip)
- [-] (resolved as invalid: it works fine when square: the meter refers to the battery box' internal power level not that of the battery inside; the level goes up fine and so does the external display which uses the image) mods/mtmachines/technic/textures/technic_battery_meter_fg.png

**Comment by poikilos** [comment]
I generated a complete list of image files that were added or changed from bucket_game-200527 to bucket_game-211111a:
<https://pastebin.com/92kv46Tv> (`wget https://pastebin.com/raw/92kv46Tv`)

**Comment by poikilos** [comment]
Here is a trimmed-down list showing only instances where the image was tall (.5 max ratio) or the destination is new (excluding dirs specified in command): <https://pastebin.com/HmB3eFLH> (`wget https://pastebin.com/raw/HmB3eFLH`)
- generated via `~/git/gimp-plugin-channel-tinker/diffimagesratio.py ../bucket_game-200527 bucket_game --max-source-ratio .5 --exclude projects --exclude src --exclude etc --exclude 3d_armor --exclude signs_lib | grep -v narrower | grep -v "[Ss]creenshot"`

**Comment by poikilos** [comment]
I'll have a list of images to revert to tall animation strips probably today: I made an image viewer. I've been wanting to do this for a while to quickly "mark"/"unmark" images then save a list of marked images. The viewer may later use my image library I use for my GIMP plugins to process images, but for now it will make an image list (WIP; see imageprocessorx.py in <https://github.com/poikilos/gimp-plugin-channel-tinker>) -- mark or unmark with up/down arrows, navigate with left or right.

**Comment by poikilos** [comment]
Ok, the list is updated and probably complete. See "From other mods" section in the original post and all `####` subsections under it.

**Comment by poikilos** [comment]
Everything seems to work in bucket_game 211114a.

**Comment by poikilos** [comment]
For historical purposes (such as avoiding having to bisect when determining which servers have the issue if you know which snapshot/release of bucket_game was used as the base) note that Slopsbucket states (via e-mail 2022-01-16):

> ...release 200513, the colour issue is not apparent there.

**Comment by poikilos** [comment]
The resizing also affected some graphics that were square before and after the change but now have scaling artifacts: #475
