### ISSUE TITLE
Fix slimenodes (Slime Buckets) Fork

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#51]
Slime buckets (poikilos fork)
- [x] https://github.com/poikilos/slimenodes/issues/1 has error: missing global buckets (so mod cannot be installed or server won't start).
- [x] (resolved: glue can be made from saplings [from upstream]) slimenodes fork: make glue replaceable with animal hide
- [x] https://github.com/poikilos/slimenodes/issues/3 disable jump or reduce bouncy value, otherwise bouncing gets higher indefinitely
- [ ] https://github.com/poikilos/slimenodes/issues/2 slime only stacks to 8 per slot

**Comment by poikilos** [comment]
- moved to https://github.com/poikilos/slimenodes/issues
