### ISSUE TITLE
The scripted resize to 32x32 caused several separate issues due to scaled textures being reduced in quality or function when resized.

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#543]
Other side effects of the scripted texture resize (or previous scaling) have been split into separate issues:
- [x] #475 (resolved; Covers textures that are resolution-dependent, so they have a functional rather than quality issue, those being palettes and animation strips)
- [x] #479 (That issue covers tools only. It lists sub-issues for specific mods and progress on those: #492, #493, #494, #495, #496)
- [x] #405 (compass texture: may be upscaling related not downscaling related)
- [x] #530 (fringes appear on edges of mobs)
- [x] #539 (butterflies: upscaling not downscaling related; started in 190620 or earlier, so wasn't from the scripted scaling)
- [x] #542 (plantlike textures and paintings aren't designed for 32x32 so they look muddy at a small scale)
- [x] (This is fixed in bucket_game snapshot 220501) Resizing the mummy caused the eyes to be distorted.

**Comment by poikilos** [comment]
All known affected textures that remained to be fixed are fixed in bucket_game snapshot 220501.
